# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rsync.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 762)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(130, 130, 527, 441))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Address = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(17)
        self.Address.setFont(font)
        self.Address.setObjectName("Address")
        self.horizontalLayout.addWidget(self.Address)
        self.Add = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.Add.setFont(font)
        self.Add.setText("")
        self.Add.setObjectName("Add")
        self.horizontalLayout.addWidget(self.Add)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.FilePath = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(17)
        self.FilePath.setFont(font)
        self.FilePath.setObjectName("FilePath")
        self.horizontalLayout_3.addWidget(self.FilePath)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.Paths = QtWidgets.QTextEdit(self.layoutWidget)
        self.Paths.setObjectName("Paths")
        self.verticalLayout.addWidget(self.Paths)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Addfiles_Button = QtWidgets.QPushButton(self.layoutWidget)
        self.Addfiles_Button.setObjectName("Addfiles_Button")
        self.horizontalLayout_2.addWidget(self.Addfiles_Button)
        self.Addfloder_Button = QtWidgets.QPushButton(self.layoutWidget)
        self.Addfloder_Button.setObjectName("Addfloder_Button")
        self.horizontalLayout_2.addWidget(self.Addfloder_Button)
        self.Clear_Button = QtWidgets.QPushButton(self.layoutWidget)
        self.Clear_Button.setObjectName("Clear_Button")
        self.horizontalLayout_2.addWidget(self.Clear_Button)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.Status = QtWidgets.QTextEdit(self.layoutWidget)
        self.Status.setObjectName("Status")
        self.verticalLayout_3.addWidget(self.Status)
        self.Start_Button = QtWidgets.QPushButton(self.layoutWidget)
        self.Start_Button.setObjectName("Start_Button")
        self.verticalLayout_3.addWidget(self.Start_Button)
        self.horizontalLayout_6.addLayout(self.verticalLayout_3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Address.setText(_translate("MainWindow", "存入地址：                                "))
        self.Add.setPlaceholderText(_translate("MainWindow", "文件将被保存至服务器中的位置"))
        self.FilePath.setText(_translate("MainWindow", "选择需要上传的本地文件："))
        self.Paths.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.Paths.setPlaceholderText(_translate("MainWindow", "点击“添加文件”以选择一个或多个文件                         点击“添加文件夹”以指定目标文件夹路径                         支持多个项目文件同时传输"))
        self.Addfiles_Button.setText(_translate("MainWindow", "添加文件"))
        self.Addfloder_Button.setText(_translate("MainWindow", "添加文件夹"))
        self.Clear_Button.setText(_translate("MainWindow", "清空列表"))
        self.Start_Button.setText(_translate("MainWindow", "开始传输"))
